[package]
name = "agave-xdphelpers"
version.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true
license.workspace = true
edition.workspace = true

[features]
agave-unstable-api = []

[dependencies]
arc-swap = { workspace = true }
agave-xdp = { workspace = true }
bytes = { workspace = true }
crossbeam-channel = { workspace = true }
log = { workspace = true }
quinn = { workspace = true }
tokio = { workspace = true, features = ["net"] }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }
caps = { workspace = true }
core_affinity = { workspace = true }

[lints]
workspace = true
